services:
  garden-yolo:
    image: ghcr.io/hartmannlight/garden-yolo:latest

    environment:
      TZ: Europe/Berlin

    volumes:
      - ./images:/opt/webcam/images
      - ./logs:/opt/webcam

    restart: unless-stopped
